const data = [
  {
    id: 1,
    name: 'La Terrasse Du Metropole',
    discount: 20,
    images: [
      require('./img/LaTerrasseDuMetropole.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '15 P. Ngô Quyền, Tràng Tiền, Hoàn Kiếm, Hà Nội',

    latitude: 21.02514853332634,
    longitude: 105.85546792484293,
    menu: [
      {
        id: 1,
        title: 'SALADE DE CRABE',
        price: 300,
        image:
          'https://cdn.pratico-pratiques.com/app/uploads/sites/3/2019/05/24133948/salade-de-crabe-avocats-et-fraises.jpg',
        description: 'King crab salad with quinoa and ginger on brioche bread',
      },
      {
        id: 2,
        title: 'RILLETTE DE SAUMON',
        price: 300,
        image:
          'https://assets.afcdn.com/recipe/20130909/55117_w1024h1024c1cx1872cy2808.webp',
        description:
          'Fresh and smoked salmon rillettes on sesame seed baguette with tomato and mandarin chutney',
      },
      {
        id: 3,
        title: 'PATÉ DE FOIE DE CANARD',
        price: 300,
        image:
          'https://www.maisonberano.com/wp-content/uploads/2017/07/pate-de-foie-gras-de-canard.jpg',
        description:
          'Duck liver pate on grilled sourdough, red wine jam, nuts and gherkins',
      },
      {
        id: 4,
        title: 'TERRINE DE FOIE GRAS',
        price: 300,
        image:
          'https://files.meilleurduchef.com/mdc/photo/recette/terrine-foie-gras-chutney-echalote/terrine-foie-gras-chutney-echalote-640.jpg',
        description:
          'Homemade foie gras terrine on toasted brioche with strawberry & pistachio',
      },
    ],
    description:
      'Minim id eiusmod laborum excepteur officia. Lorem ad enim voluptate elit sunt velit nostrud voluptate. Ut nostrud et aliqua do eiusmod laboris magna occaecat aliquip. Reprehenderit veniam veniam cupidatat labore dolore aute laboris voluptate consectetur consectetur elit.',
    rating: 4.7,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '09:00',
          timeEnd: '12:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'unavailable'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'unavailable'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'unavailable'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'unavailable'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'available'},
            {id: 16, name: '16', status: 'unavailable'},
          ],
        },
        {
          id: 2,
          timeStart: '12:00',
          timeEnd: '15:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'available'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'available'},
            {id: 7, name: '07', status: 'unavailable'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '15:00',
          timeEnd: '17:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '09:00',
      close_time: '17:00',
    },
  },
  {
    id: 2,
    name: 'Hanoi Social Club',
    discount: 30,
    images: [
      require('./img/HanoiSocialClub.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '6 Ng. Hội Vũ, Hàng Bông, Hoàn Kiếm, Hà Nội',

    latitude: 21.029344299900394,
    longitude: 105.84602042484299,
    menu: [
      {
        id: 1,
        title: 'Vegan mushroom pasta',
        price: 300,
        image:
          'https://d1sag4ddilekf6.azureedge.net/compressed_webp/items/VNITE20211019060158358566/detail/menueditor_item_613db8400130480fb8d08b9fed72bc1f_1636288082903568549.webp',
        description:
          'Mushrooms with cashew cream sauce, tarragon leaves, chives and white wine. Can be served with parmesan cheese. Vegetarian dishes without eggs and milk',
      },
      {
        id: 2,
        title: 'Linguine puttanesca',
        price: 300,
        image:
          'https://d1sag4ddilekf6.azureedge.net/compressed_webp/items/VNITE20211019060158434715/detail/menueditor_item_df0576993dfb40d0b3ba4acb9e699fa7_1636288054854465017.webp',
        description: 'Fresh tomatoes with anchovies, caper and chili sauce',
      },
      {
        id: 3,
        title: 'Cherry tomato pasta',
        price: 300,
        image:
          'https://d1sag4ddilekf6.azureedge.net/compressed_webp/items/VNITE20211019060159049058/detail/menueditor_item_139c9f43ad72413e8acd41f0e0d2460e_1636288100553443657.webp',
        description: 'Cherry tomatoes, thyme, olives and parmesan cheese',
      },
      {
        id: 4,
        title: 'Lentil pasta',
        price: 300,
        image:
          'https://d1sag4ddilekf6.azureedge.net/compressed_webp/items/VNITE20211019060159184853/detail/menueditor_item_072911e34ded416c944b62c1bbdb9273_1636288694523242104.webp',
        description:
          'Tomato sauce flavored with cumin and coriander served with yogurt and parsley',
      },
    ],
    description:
      'Id amet veniam nisi esse ea. Ex est ut cupidatat sint culpa commodo exercitation est magna proident officia laboris. Exercitation laboris ex laborum qui mollit et occaecat deserunt incididunt. Mollit excepteur sunt adipisicing ullamco excepteur non ex proident. Irure laborum enim do fugiat aute amet eu quis amet tempor.',
    rating: 4.7,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '17:00',
          timeEnd: '19:00',

          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '19:00',
          timeEnd: '21:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '21:00',
          timeEnd: '22:30',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '17:00',
      close_time: '22:30',
    },
  },
  {
    id: 3,
    name: 'The Rhythms Restaurant',
    discount: 10,
    images: [
      require('./img/the-rhythms-restaurant.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '7th floor, 33-35 P. Hàng Dầu, Hoàn Kiếm, Hà Nội',

    latitude: 21.031348882795474,
    longitude: 105.8539987690218,
    menu: [
      {
        id: 1,
        title: 'AMERICAN TOP BLADE STEAK',
        price: 300,
        image:
          'https://gofood.vn//uploads/tong-hop-tin-tuc/thong-tin-san-pham/top-blade-black-angus-1.jpg',
        description:
          'Top blade, thyme, baked potato, asparagus, mushroom, baby carrot, Dalat vegetable, pumpkin puree.',
      },
      {
        id: 2,
        title: 'GRILLED RACK OF LAMB',
        price: 300,
        image:
          'https://basilandbubbly.com/wp-content/uploads/2021/07/grilled-rack-of-lamb-2.jpg',
        description:
          'Australian lamb, mustard, garlic, butter, thyme, mashed sweet potato, pumpkin puree, asparagus, Dalat vegetable, pistachio crust.',
      },
      {
        id: 3,
        title: 'TUNA STEAK',
        price: 300,
        image:
          'https://www.acouplecooks.com/wp-content/uploads/2022/04/Tuna-Steak-008d.jpg',
        description:
          'Tuna steak, butter, sesame, baby carrot, Dalat vegetable, pea puree, ginger, Teriyaki sauce.',
      },
      {
        id: 4,
        title: 'TOM YUM SOUP',
        price: 300,
        image:
          'https://www.lemonblossoms.com/wp-content/uploads/2017/11/Tom-Yum-Soup-S1-2.jpg',
        description:
          'Tiger prawns, lemongrass, chili peppers, lime leaves, mushrooms, baby corn, coconut milk, fresh lime.',
      },
    ],
    description:
      'Duis enim eiusmod do tempor aliqua exercitation non sunt duis excepteur eu cillum ad. Laboris sit mollit et qui quis ipsum nisi occaecat sunt et proident voluptate ipsum eiusmod. Non officia ullamco pariatur pariatur consectetur ea. Cupidatat in irure sint reprehenderit fugiat reprehenderit aute. Est minim id adipisicing aliqua ut in deserunt dolore aliquip exercitation Lorem. Fugiat tempor excepteur magna nisi.',
    rating: 4.7,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '12:00',
          timeEnd: '16:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '16-00',
          timeEnd: '20:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '20:00',
          timeEnd: '22:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '12:00',
      close_time: '22:00',
    },
  },
  {
    id: 4,
    name: 'Chestnut Restaurant',
    discount: 25,
    images: [
      require('./img/chestnut.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: 'Số 6 Hàng Bè, P. Lý Thái Tổ, Q. Hoàn Kiếm, Hà Nội',

    latitude: 21.033796223443126,
    longitude: 105.85377354018605,
    menu: [
      {
        id: 1,
        title: 'CHESTNUT PAELLA',
        price: 300,
        image:
          'https://images.squarespace-cdn.com/content/v1/58bb9ccab3db2b08879d6fdd/1490453728385-X8TYVFPTR76T3AH1J61X/image-asset.jpeg',
        description:
          'Braised Rabbit, Fennel Roasted Pork Shoulder, Spanish Saffron Rice, Spring Onions, Snap Peas, Artichokes, Asparagus, Blistered Tomatoes, Rosemary Marcona Crumble, Micro Sorrel',
      },
      {
        id: 2,
        title: 'SWEET POTATO SOPE',
        price: 300,
        image:
          'https://deliciouslittlebites.com/wp-content/uploads/2017/08/Barbecue-Pulled-Pork-Sweet-Potato-Rounds-Recipe-Image-4-500x500.jpg',
        description:
          'Chipotle Sweet Potato Puree, House Made Pork Chorizo, Tomatillo Salsa, Cilantro Lime Crema, Cotija, Micro Cilantro',
      },
      {
        id: 3,
        title: 'CHESTNUT KOBE BURGER',
        price: 300,
        image:
          'https://scontent-tpe1-1.xx.fbcdn.net/v/t39.30808-6/329026020_767162541496719_1072935012747541280_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=730e14&_nc_ohc=wT99dyyqnDgAX_NiQH-&_nc_ht=scontent-tpe1-1.xx&oh=00_AfC_Of2CHfrcpSI6RHIUgrwVb6H_Eae5PW4GjlKNCo90tg&oe=640F29A4',
        description:
          '8 oz Patty, Baby Arugula, Mediterranean Salad, Spring Onioin Tzatziki, Griddled Bread Cheese, Brioche Bun, Truffle Fries',
      },
      {
        id: 4,
        title: 'PETITE NY STRIP',
        price: 300,
        image:
          'https://www.christensenranch.com/wp-content/uploads/2017/05/new-york-strip-steak-cooked.jpg',
        description:
          '4oz, Confit Fingerling Potatoes, Haricots Verts, Red Wine Demi, Truffle Chive Butter',
      },
    ],
    description:
      'Nulla incididunt magna in sit. Magna aliquip cillum mollit est ad in tempor ea. Duis aliqua id sit anim duis enim qui dolor adipisicing quis tempor aliquip officia reprehenderit. Pariatur consectetur laboris culpa sunt occaecat laboris aute proident ex dolore aliquip culpa dolore. Eu proident ipsum sunt ex nulla dolor exercitation reprehenderit ipsum mollit aute proident ea minim. Tempor occaecat adipisicing dolor pariatur officia eiusmod. Elit elit quis ullamco elit mollit occaecat.',
    rating: 4.7,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '13:00',
          timeEnd: '16:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '16-00',
          timeEnd: '20:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '20:00',
          timeEnd: '22:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '13:00',
      close_time: '22:00',
    },
  },
  {
    id: 5,
    name: 'Red Bean Restaurant',
    discount: 20,
    images: [
      require('./img/red-bean-2.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '94 Mã Mây, Quận Hoàn Kiếm, Hà Nội',

    latitude: 21.034415750598825,
    longitude: 105.85316058251456,
    menu: [
      {
        id: 1,
        title: 'AMERICAN TOP BLADE STEAK',
        price: 300,
        image:
          'https://gofood.vn//uploads/tong-hop-tin-tuc/thong-tin-san-pham/top-blade-black-angus-1.jpg',
        description:
          'Top blade, thyme, baked potato, asparagus, mushroom, baby carrot, Dalat vegetable, pumpkin puree.',
      },
      {
        id: 2,
        title: 'GRILLED RACK OF LAMB',
        price: 300,
        image:
          'https://basilandbubbly.com/wp-content/uploads/2021/07/grilled-rack-of-lamb-2.jpg',
        description:
          'Australian lamb, mustard, garlic, butter, thyme, mashed sweet potato, pumpkin puree, asparagus, Dalat vegetable, pistachio crust.',
      },
      {
        id: 3,
        title: 'TUNA STEAK',
        price: 300,
        image:
          'https://www.acouplecooks.com/wp-content/uploads/2022/04/Tuna-Steak-008d.jpg',
        description:
          'Tuna steak, butter, sesame, baby carrot, Dalat vegetable, pea puree, ginger, Teriyaki sauce.',
      },
      {
        id: 4,
        title: 'TOM YUM SOUP',
        price: 300,
        image:
          'https://www.lemonblossoms.com/wp-content/uploads/2017/11/Tom-Yum-Soup-S1-2.jpg',
        description:
          'Tiger prawns, lemongrass, chili peppers, lime leaves, mushrooms, baby corn, coconut milk, fresh lime.',
      },
    ],
    description:
      'Minim id eiusmod laborum excepteur officia. Lorem ad enim voluptate elit sunt velit nostrud voluptate. Ut nostrud et aliqua do eiusmod laboris magna occaecat aliquip. Reprehenderit veniam veniam cupidatat labore dolore aute laboris voluptate consectetur consectetur elit.',
    rating: 4.7,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '18:00',
          timeEnd: '20:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '20-00',
          timeEnd: '21:30',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '21:30',
          timeEnd: '23:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '18:00',
      close_time: '23:00',
    },
  },
  {
    id: 6,
    name: 'Green Tangerine',
    discount: 30,
    images: [
      require('./img/green-tangerine.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '48 P. Hàng Bè, Hàng Bạc, Hoàn Kiếm, Hà Nội',

    latitude: 21.032908894628598,
    longitude: 105.85373616902177,
    menu: [
      {
        id: 1,
        title: 'AMERICAN TOP BLADE STEAK',
        price: 300,
        image:
          'https://gofood.vn//uploads/tong-hop-tin-tuc/thong-tin-san-pham/top-blade-black-angus-1.jpg',
        description:
          'Top blade, thyme, baked potato, asparagus, mushroom, baby carrot, Dalat vegetable, pumpkin puree.',
      },
      {
        id: 2,
        title: 'GRILLED RACK OF LAMB',
        price: 300,
        image:
          'https://basilandbubbly.com/wp-content/uploads/2021/07/grilled-rack-of-lamb-2.jpg',
        description:
          'Australian lamb, mustard, garlic, butter, thyme, mashed sweet potato, pumpkin puree, asparagus, Dalat vegetable, pistachio crust.',
      },
      {
        id: 3,
        title: 'TUNA STEAK',
        price: 300,
        image:
          'https://www.acouplecooks.com/wp-content/uploads/2022/04/Tuna-Steak-008d.jpg',
        description:
          'Tuna steak, butter, sesame, baby carrot, Dalat vegetable, pea puree, ginger, Teriyaki sauce.',
      },
      {
        id: 4,
        title: 'TOM YUM SOUP',
        price: 300,
        image:
          'https://www.lemonblossoms.com/wp-content/uploads/2017/11/Tom-Yum-Soup-S1-2.jpg',
        description:
          'Tiger prawns, lemongrass, chili peppers, lime leaves, mushrooms, baby corn, coconut milk, fresh lime.',
      },
    ],
    description:
      'Id amet veniam nisi esse ea. Ex est ut cupidatat sint culpa commodo exercitation est magna proident officia laboris. Exercitation laboris ex laborum qui mollit et occaecat deserunt incididunt. Mollit excepteur sunt adipisicing ullamco excepteur non ex proident. Irure laborum enim do fugiat aute amet eu quis amet tempor.',
    rating: 5,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '09:00',
          timeEnd: '12:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '12-00',
          timeEnd: '15:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '15:00',
          timeEnd: '17:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '09:00',
      close_time: '17:00',
    },
  },
  {
    id: 7,
    name: 'Home Hanoi Restaurant',
    discount: 10,
    images: [
      require('./img/home.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '34 Châu Long, Quận Ba Đình, Hà Nội',

    latitude: 21.045742849295877,
    longitude: 105.84239992669345,
    menu: [
      {
        id: 1,
        title: 'AMERICAN TOP BLADE STEAK',
        price: 300,
        image:
          'https://gofood.vn//uploads/tong-hop-tin-tuc/thong-tin-san-pham/top-blade-black-angus-1.jpg',
        description:
          'Top blade, thyme, baked potato, asparagus, mushroom, baby carrot, Dalat vegetable, pumpkin puree.',
      },
      {
        id: 2,
        title: 'GRILLED RACK OF LAMB',
        price: 300,
        image:
          'https://basilandbubbly.com/wp-content/uploads/2021/07/grilled-rack-of-lamb-2.jpg',
        description:
          'Australian lamb, mustard, garlic, butter, thyme, mashed sweet potato, pumpkin puree, asparagus, Dalat vegetable, pistachio crust.',
      },
      {
        id: 3,
        title: 'TUNA STEAK',
        price: 300,
        image:
          'https://www.acouplecooks.com/wp-content/uploads/2022/04/Tuna-Steak-008d.jpg',
        description:
          'Tuna steak, butter, sesame, baby carrot, Dalat vegetable, pea puree, ginger, Teriyaki sauce.',
      },
      {
        id: 4,
        title: 'TOM YUM SOUP',
        price: 300,
        image:
          'https://www.lemonblossoms.com/wp-content/uploads/2017/11/Tom-Yum-Soup-S1-2.jpg',
        description:
          'Tiger prawns, lemongrass, chili peppers, lime leaves, mushrooms, baby corn, coconut milk, fresh lime.',
      },
    ],
    description:
      'Duis enim eiusmod do tempor aliqua exercitation non sunt duis excepteur eu cillum ad. Laboris sit mollit et qui quis ipsum nisi occaecat sunt et proident voluptate ipsum eiusmod. Non officia ullamco pariatur pariatur consectetur ea. Cupidatat in irure sint reprehenderit fugiat reprehenderit aute. Est minim id adipisicing aliqua ut in deserunt dolore aliquip exercitation Lorem. Fugiat tempor excepteur magna nisi.',
    rating: 4.0,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '10:00',
          timeEnd: '12:30',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'unavailable'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '12-30',
          timeEnd: '15:30',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'unavailable'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '15:30',
          timeEnd: '18:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'unavailable'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '10:00',
      close_time: '18:00',
    },
  },
  {
    id: 8,
    name: 'Essence Restaurant',
    discount: 45,
    images: [
      require('./img/essence-2.jpg'),
      require('./img/example.png'),
      require('./img/example2.png'),
    ],
    location: '38A P. Trần Phú, Điện Biên, Ba Đình, Hà Nội',

    latitude: 21.030904098415586,
    longitude: 105.84134281135023,
    menu: [
      {
        id: 1,
        title: 'AMERICAN TOP BLADE STEAK',
        price: 300,
        image:
          'https://gofood.vn//uploads/tong-hop-tin-tuc/thong-tin-san-pham/top-blade-black-angus-1.jpg',
        description:
          'Top blade, thyme, baked potato, asparagus, mushroom, baby carrot, Dalat vegetable, pumpkin puree.',
      },
      {
        id: 2,
        title: 'GRILLED RACK OF LAMB',
        price: 300,
        image:
          'https://basilandbubbly.com/wp-content/uploads/2021/07/grilled-rack-of-lamb-2.jpg',
        description:
          'Australian lamb, mustard, garlic, butter, thyme, mashed sweet potato, pumpkin puree, asparagus, Dalat vegetable, pistachio crust.',
      },
      {
        id: 3,
        title: 'TUNA STEAK',
        price: 300,
        image:
          'https://www.acouplecooks.com/wp-content/uploads/2022/04/Tuna-Steak-008d.jpg',
        description:
          'Tuna steak, butter, sesame, baby carrot, Dalat vegetable, pea puree, ginger, Teriyaki sauce.',
      },
      {
        id: 4,
        title: 'TOM YUM SOUP',
        price: 300,
        image:
          'https://www.lemonblossoms.com/wp-content/uploads/2017/11/Tom-Yum-Soup-S1-2.jpg',
        description:
          'Tiger prawns, lemongrass, chili peppers, lime leaves, mushrooms, baby corn, coconut milk, fresh lime.',
      },
    ],
    description:
      'Nulla incididunt magna in sit. Magna aliquip cillum mollit est ad in tempor ea. Duis aliqua id sit anim duis enim qui dolor adipisicing quis tempor aliquip officia reprehenderit. Pariatur consectetur laboris culpa sunt occaecat laboris aute proident ex dolore aliquip culpa dolore. Eu proident ipsum sunt ex nulla dolor exercitation reprehenderit ipsum mollit aute proident ea minim. Tempor occaecat adipisicing dolor pariatur officia eiusmod. Elit elit quis ullamco elit mollit occaecat.',
    rating: 3.5,
    times: {
      shift: [
        {
          id: 1,
          timeStart: '09:00',
          timeEnd: '12:00',
          tables: [
            {id: 1, name: '01', status: 'available'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'available'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'available'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 2,
          timeStart: '12-00',
          timeEnd: '15:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'unavailable'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'unavailable'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'unavailable'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
        {
          id: 3,
          timeStart: '15:00',
          timeEnd: '17:00',
          tables: [
            {id: 1, name: '01', status: 'unavailable'},
            {id: 2, name: '02', status: 'available'},
            {id: 3, name: '03', status: 'available'},
            {id: 4, name: '04', status: 'available'},
            {id: 5, name: '05', status: 'unavailable'},
            {id: 6, name: '06', status: 'unavailable'},
            {id: 7, name: '07', status: 'available'},
            {id: 8, name: '08', status: 'unavailable'},
            {id: 9, name: '09', status: 'unavailable'},
            {id: 10, name: '10', status: 'available'},
            {id: 11, name: '11', status: 'available'},
            {id: 12, name: '12', status: 'unavailable'},
            {id: 13, name: '13', status: 'available'},
            {id: 14, name: '14', status: 'unavailable'},
            {id: 15, name: '15', status: 'available'},
            {id: 16, name: '16', status: 'available'},
          ],
        },
      ],
      open_time: '09:00',
      close_time: '17:00',
    },
  },
];

export default data;
